apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test102602-ingress
spec:
  ingressClassName: ingress-internal
  rules:
  - host: test102602.cepg-aa.kubepia.net
    http:
      paths:
      - path: /
        backend:
          service:
            name: test102602
            port:
              number: 8080
        pathType: Prefix
